### ISSUE TITLE
----

### ISSUE THREAD

**Issue by amitguptagwl** [update/update#19]

**Comment by jonschlinkert** [comment]
don't ever post information about a potential vulnerability before it has been handled discreetly by a maintainer!!!!!

https://en.wikipedia.org/wiki/Responsible_disclosure

edit: it's worse! Not only did you broadcast a potential vulnerability on an issue, but it has nothing to do with this library, it was already resolved months ago by that library, which it extremely clearly says on snyk, and users will automatically get that code, there is no need for anyone to do anything at all. 

Why is it hard to rtfm before posting issues like this? Moreover, it was disputed whether or not it was even a vulnerability, despite what it says on the snyk page. The person that contact me was getting paid by snyk (since they are literally running automated software on people's code to find regex that can potentially catastrophically backtrack - this is highly suspect as it's _very, very easy to register an alarming score when using methods like those in https://www.npmjs.com/package/safe-regex_). Anyone could take advantage of that information to contrive patterns that cause catostrophic backtracking in literally hundreds of thousands of regex's in projects published on Github. But that alone does not remotely qualify as a vulnerability, even if the regex in question can freeze up a server. Why? Because users actually need to be able to access that API for it to happen, and in this case it's highly debatable. 1) there was already a check for potentially unsafe strings, 2) there is (and always was) an option to prevent strings longer than `n` from being passed, 3) most importantly, I was unable to reproduce the "vulnerability. On my machine it took something like 300ms to process. That's very slow for a regex, agreed, and the argument was that a DDoS could take advantage of that. But if we're being remotely pragmatic, whoever is either allowing someone to pass brace patterns and globs on a web form and/or is not limiting the size of the inputs to something less than, say, 65,000 characters has bigger problems to worry about.
