### ISSUE TITLE
[Suggestion] Choose template for update

### ISSUE THREAD

**Issue by stefanwalther** [update/update#6]
One feature I am in general missing in generate/update:

- Let's say I have different project types
- Depending on the project type I'd like to add different templates for a `.gitignore`
- Then I'd like to do something like `update editorconfig --t=gitignore_projectTypeA`
(Then the template `gitignore_projectTypeA` from `~\templates` would be taken).

Is this something which is already possible resp. you are considering to implement?

**Comment by jonschlinkert** [comment]
> Is this something which is already possible

well, kind of. Currently [generate checks](https://github.com/generate/generate/blob/master/lib/mixins.js#L61-L64) the `~/generate/templates` directory for a template, using an `.onLoad` middleware. Now that I've gotten some experience with generate I know it would be better to use `.onStream` for that check, since `.onLoad` won't always be called. 

This isn't a perfect solution though, and it doesn't "toggle" based on the project. But that's a great idea, and I think we can implement that in a way that's intuitive. But let me think about it first... (and feel free to share your thoughts too).

Basically, all the `.onLoad` middleware does is replace `file.contents` with the contents of the custom template if one exists. It's a nice solution, since it doesn't require implementors to write code for this in every updater/generator. 

A couple of thoughts:

- Should `update` and `generate` should have different templates directories? 
- Should we support all of the above?  `~/templates`, `~/update/templates` and `~/generate/templates`?
- Should we only support `~/update/templates` and `~/generate/templates`, and also add support for global "user plugins", that would allow you to define any custom code you want, to be loaded before any generators or updaters? This way you can resolve paths however you want.
- @doowb and I have been planning on adding support for "custom" scaffolds and boilerplates as well. For example, you might define a scaffold in `~/generate/scaffolds` that would either be used automatically when you run `generate-project`, or would be used when a certain command is given. Not sure about this yet, but it will be really useful

Thoughts? I'd like to learn more about how you think it should be done so we can improve experience.

**Comment by stefanwalther** [comment]
> Should update and generate should have different templates directories?
Right now I think the update and generate examples overlap quite a bit, so it is (for newbies like me) not clear what the differentiator between update and generate will be. So updaters use under the hood the generators or reference them.

> Should we support all of the above? ~/templates, ~/update/templates and ~/generate/templates?
I think that's just confusing (if this works by default)

> Should we only support ~/update/templates and ~/generate/templates, and also add support for global "user plugins", that would allow you to define any custom code you want, to be loaded before any generators or updaters? This way you can resolve paths however you want.
I have seen that you have recently create the node-toolkit repo as some kind of umbrella of all the projects. What's about just allowing

- `.node-toolkit/templates` - as global templates (prio 3)
- `.node-toolkit/update/templates` - as update templates (prio 2)
- then the default templates of update

Anyhow, the root directory should be a hidden one, so starting with a `.` ... otherwise it gets to messy.

**Comment by jonschlinkert** [comment]
> Right now I think the update and generate examples overlap quite a bit

Both are built on `Base`. Base plugins are used on both applications. Examples are going to be similar, which is a pretty awesome advantage, don't you think? We're more than happy to take prs for improvements to docs.

> it is (for newbies like me) not clear what the differentiator between update and generate will be. 

This should help: 

- `generate`: "generates" things
- `update`: "updates" things

When you run the `generate` command, you would expect something to be created.
When you run the `update` command, you would expect existing files to be modified.

If you need more info, the readmes describe in detail what each project does:

- https://github.com/update/update#what-does-update-do
- https://github.com/generate/generate#what-is-generate

> So updaters use under the hood the generators or reference them.

No, neither. As an "updater" implementor you can use gulp or `fs` or anything you want to generate files when you need to create something new in your updater. In the generators I created, I thought it made sense to use a Generate generator, given that they are compatible. 

> I think that's just confusing (if this works by default)

so, when a user, who has no knowledge of `Generate` is running `update`, you think that using `~/update/templates`, falling back on `~/templates` is confusing? Or were you thinking that I meant we should use `~/update/templates` for Generate? That would indeed be confusing.

We can keep this open until a solution is implemented

**Comment by stefanwalther** [comment]
Hmm, have to continue thinking of this ... Will probably have a better answer as soon as I have created some generators and updaters ...

**Comment by tunnckoCore** [comment]
I'm also for hidden place. I also seen that `node-toolkit` org recently.

But about the paths. For me it make best sense if it follow some convention like that `~/.node-toolkit/update/updater-name-or-generator-name/templates`, because the structure of the repos are the same. But also seeing why `~/.node-toolkit/update/templates` is good too.

**Comment by stefanwalther** [comment]
Hi,

any decision on how to proceed with the location of templates? (also see https://github.com/update/updater-editorconfig/issues/1)

Actually, this is the only thing holding me off creating some updaters, and I just can't wait **finally** consolidating all my libraries ;-)

**Comment by jonschlinkert** [comment]
https://github.com/update/update/blob/master/CHANGELOG.md#070---2016-07-21

**Comment by stefanwalther** [comment]
Great, thx.

**Comment by jonschlinkert** [comment]
One more thought using generators inside updaters. 

I'm about to publish `update-gitignore`, which is this:

```js
module.exports = function(app) {
  if (!isValid(app, 'updater-gitignore')) return;
  app.use(conflicts());
  app.use(require('generate-gitignore'));
};
```

In this case it makes sense to "proxy" a generator as an updater, for a couple of reasons:

- this allows you to use generate with Update's CLI to provide a consistent experience (e.g. just run `update`)
- I don't currently have a better solution for "updating" a `.gitignore` file. (comments below)


Regarding updating a `.gitignore`, right now I just want to get this working so this will just overwrite the current `.gitignore` with a template. I do have a project that parses `.gitignore`, which could allow us to "update" a gitignore file that without overwriting any custom patterns in it. For this to work, we'd either need to follow a convention, like adding custom patterns after a `# custom` comment, or we could do the opposite and only add patterns from the template if they're missing in `.gitignore`. Anyway, I don't have time to do this yet, but I'd like to.

hope this makes sense

**Comment by stefanwalther** [comment]
Yes, makes a lot of sense, thx for clarification.
